---
- name: Clean up the repos
  file:
    path: /etc/yum.repos.d/{{ item }}
    state: absent
    with_items: "{{ repos }}"

- name: Template script to setup repos
  get_url:
    url: "{{ item }}"
    dest: "{{ yum_repo_path }}"
    with_items: "{{ repos_url }}"

- name: Clean yum cache
  shell: yum clean all
