---
- name: Execute yum update on the undercloud
  yum: name=* state=latest

- name: Upgrade the undercloud
  sudo: yes
  sudo_user: "{{ undercloud_upgrade_user }}"
  shell: openstack undercloud install &> upgrade_undercloud.log
  when: step_upgrade_undercloud
  notify:
    - restart openstack services
